### ISSUE TITLE
NMS Leviathan Crash

### ISSUE THREAD

**Issue by CPTPiett** [cwmonkey/nms-expeditions#18]
First of all I want to say thanks for giving all us the opportunity to play expeditions we didn't have a chance to play when they came out. I've been doing them in order and so far they all work great.

As far as Leviathan, when I attempt to collect the final reward the game INSTANTLY crashes. The error it gives me is 132250_0x76B914_ST76561197983859525.

Now it isn't the end of the world since it DID give me the frigate when I switched to normal save so it isn't a total loss. I just can't finish the expedition nor import any of the items I collected during the expedition.

Just wondering if you've come across this since the last time you had a chance to look at it. Thanks!

**Comment by cwmonkey** [comment]
Yep, this is explained on the site when you click expedition 7 (and lower on the page along with the other notes): https://cwmonkey.github.io/nms-expeditions/

You should still be able to pass items back to your main save. Just put them in the terminal on the Anomaly then switch back to your primary save in the pause menu. You can actually do this at any point during the expedition (an epiphany I had today when I was struggling with inventory space).

To finish the expedition, just open the game while in online mode and it will kick you out without claiming the final milestone reward (make sure you do the item thing before going online).

Unfortunately, this cannot be "fixed" since this is not a mod (you can think of it more like a config hack, rather than a code change). The reward itself is broken somehow - something they may fix if they ever re-redux the expedition again, or offer the same reward in a new expedition.

**Comment by CPTPiett** [comment]
Thanks for answering. It won't let me load anything into the inventory
slots at the expedition kiosk. A square will slightly change color when I
hover the mouse cursor over it but when I click on it, nothing happens. The
only time I was able to send things back to my main save in previous
expeditions was when it was completed and the final reward was claimed.

It's all good though. Got to play it through without it wrecking my save
file so it ain't all bad!

**Comment by cwmonkey** [comment]
Ah, just tested and you're right about passing items back. I guess I got confused as to which state I was in when I was passing items back to my primary save.

I think this means my patch swapping rewards around didn't really accomplish anything 🤔 I'll try swapping them back and just making the quest optional to see if that will allow you to send items back and/or end the expedition.

**Comment by CPTPiett** [comment]
Sounds great. You were right about going online. It finished the expedition
and gave me all the rewards, credits, and nanites. Only thing I didn't get
was the items in the inventory so I still call that a win. Thanks for all
the hard work!

**Comment by cwmonkey** [comment]
ok, just tested a slightly different approach and it worked. Some of the rewards were arranged and the second to the last milestone in phase 5 now rewards the frigate and has been made optional. This lets you end the expedition AND transfer items via the terminal. Here is what it looks like:

1. Once the now optional frigate milestone is finished, it will look like this: ![lev1](https://github.com/user-attachments/assets/0a61ec2e-28bc-49d3-9428-18da37ad4a68)
2. Once all your milestones are finished, go to the expedition terminal on the Anomaly and choose "End Expedition": 
![lev2](https://github.com/user-attachments/assets/258cc42a-dee0-49ea-959e-1a83113b1bc3)
3. You will get this message reassuring you that you will be allowed to transfer items: 
![lev3](https://github.com/user-attachments/assets/5993f367-dc49-488e-b6fe-a7c8810057df)
4. Once you click "Accept" the terminal interface will look like this and you can transfer items: 
![lev4](https://github.com/user-attachments/assets/e6e68536-499c-4070-884d-2c46d6161dfa)

The expedition file/patch/notices have been updated on my site: https://cwmonkey.github.io/nms-expeditions/

Thanks for reporting this issue @CPTPiett - I think this is about as good as it can get without writing a mod to fix the reward or waiting for HG to fix or add a new reward with the same item.

**Comment by cwmonkey** [comment]
HG fixed this so I removed my patch.

**Comment by CPTPiett** [comment]
Awesome, thanks for the update!
